### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Tammo0987** [Paul2708/analysis-exercises#1]
Typo at line 59 ;)

**Comment by Paul2708** [comment]
Before uploading the file (here), I will check on typos. I think there are lot more.
Fixed it anyways - thanks!

**Comment by Paul2708** [comment]
Fixed all found typos. :D (see https://github.com/Paul2708/analysis-exercises/commit/7ccaffbd04f8b6d6aa3357b8cbf8c951d502e27f)
